# Generated by Django 5.0.4 on 2024-07-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0003_account_is_connected'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='elo',
            field=models.IntegerField(default=1000),
        ),
    ]
