# Generated by Django 5.0.4 on 2024-07-23 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0004_account_elo'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='nb_top1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='nb_top2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='nb_top4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='nb_top8',
            field=models.IntegerField(default=0),
        ),
    ]
