# Generated by Django 5.0.4 on 2024-07-17 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0004_account_elo'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='coef',
            field=models.IntegerField(default=40),
        ),
        migrations.AddField(
            model_name='account',
            name='nb_games',
            field=models.IntegerField(default=0),
        ),
    ]
