# Generated by Django 5.0.4 on 2024-07-28 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0005_account_coef_account_nb_games'),
        ('myaccount', '0005_account_nb_top1_account_nb_top2_account_nb_top4_and_more'),
    ]

    operations = [
    ]
