# Generated by Django 5.0.4 on 2024-07-28 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0006_merge_20240727_2253'),
        ('myaccount', '0006_merge_20240728_0909'),
    ]

    operations = [
    ]
