# Generated by Django 5.0.4 on 2024-05-13 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_delete_button'),
    ]

    operations = [
        migrations.DeleteModel(
            name='algorithm',
        ),
    ]
