# Generated by Django 5.0.4 on 2024-05-21 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_delete_algorithm'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ball',
        ),
        migrations.DeleteModel(
            name='pad',
        ),
    ]
