# Generated by Django 5.0.4 on 2024-06-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partie',
            options={'ordering': ['-time'], 'verbose_name': 'Game', 'verbose_name_plural': 'Games'},
        ),
        migrations.AddField(
            model_name='partie',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
