# Generated by Django 5.0.4 on 2024-06-22 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_alter_partie_player1_alter_partie_player2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partie',
            name='player1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='partie',
            name='player2',
            field=models.CharField(max_length=100),
        ),
    ]
