# Generated by Django 5.0.4 on 2024-08-03 14:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_partie_moyenne_echange_partie_order_points_scored_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partie',
            name='nb_echange_per_point',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
    ]
