# Generated by Django 5.0.4 on 2024-08-03 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_partie_nb_echange_per_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partie',
            name='moyenne_echange',
        ),
        migrations.RemoveField(
            model_name='partie',
            name='nb_echange_per_point',
        ),
        migrations.RemoveField(
            model_name='partie',
            name='order_points_scored',
        ),
        migrations.RemoveField(
            model_name='partie',
            name='timers',
        ),
    ]
