# Generated by Django 5.0.4 on 2024-08-03 14:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_remove_partie_moyenne_echange_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partie',
            name='moyenne_echange',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='partie',
            name='nb_echange_per_point',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
        migrations.AddField(
            model_name='partie',
            name='order_points_scored',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None),
        ),
        migrations.AddField(
            model_name='partie',
            name='timers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
    ]
