# Generated by Django 5.0.4 on 2024-05-09 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatemessage',
            name='message',
            field=models.CharField(),
        ),
    ]
