# Generated by Django 5.0.4 on 2024-06-26 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_conversation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
