# Generated by Django 5.0.4 on 2024-06-26 22:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_conversation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
